# This file is expected to fail âŒ upon push until you fix the bug
# You successfully completed this level when this file pass ğŸŸ¢ upon push
name: HACK - Jarvis Gone Wrong

on:
  push:
    paths:
      - ".github/workflows/jarvis-code.yml"

jobs:
  jarvis:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Check out code
        uses: actions/checkout@v3
